//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long Id { get; set; }
        public string NAME { get; set; }
        public decimal Salary { get; set; }
        public long DepId { get; set; }
        public System.DateTime JoiningDate { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
