//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilege
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Privilege()
        {
            this.UserRolePrivileges = new HashSet<UserRolePrivilege>();
        }
    
        public long PK_PrivilegeID { get; set; }
        public string PrivilegeName { get; set; }
        public string MenuName { get; set; }
        public Nullable<bool> IsPage { get; set; }
        public Nullable<bool> IsFunction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRolePrivilege> UserRolePrivileges { get; set; }
    }
}
